config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/auth/:provider'          => 'omniauth#auth', as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  attachment :house_image

  validates :address, presence: true
  validates_length_of :price, :maximum => 999_999_999_999_999_999, :allow_blank => true
  validates :price , presence: true
  validates :agent, presence: true
  validates :description, presence: true
  validates :space, presence: true
  validates :parking, presence: true
  validates :bedrooms, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Factory method to create a user from some omniauth data
  # Omniauth will use this to build a *NEW* user for us
  def self.from_omniauth(authentication_data)
    user = User.where(provider: authentication_data['provider'],
                      uid: authentication_data['uid']).first_or_create

    Rails.logger.debug "The user is #{user.inspect}"

    user.name         = authentication_data.info.name
    user.nickname     = authentication_data.info.nickname
    user.access_token = authentication_data.info.access_token

    user.save!

    Rails.logger.debug "After saving, the user is #{user.inspect}"

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # Assign the current user
  def current_user=(user)
    session[:user_id] = user.id
  end

  def current_user
  @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  # Returns a boolean representing if the user is logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  # Method to use in filter to ensure the user is logged in
  def authenticate!
    unless logged_in?
      redirect_to login_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  before_action :authenticate!, except: [:index]

  def index
    @homes = Home.all
  end

  # GET /homes/1
  def show
    @home = Home.find(params[:id])
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  def create
    @home = Home.new(home_params)

    if @home.save
      redirect_to @home, notice: 'Home was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /homes/1
  def update
    @home = Home.find(params[:id])
    if @home.update(home_params)
      redirect_to @home, notice: 'Home was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /homes/1
  def destroy
    @home = Home.find(params[:id])
    @home.destroy
    redirect_to homes_url, notice: 'Home was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def home_params
      params.require(:home).permit(:address, :price, :agent, :description, :space, :parking, :bedrooms, :bathrooms, :house_image)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # Show the failure page
  def failure
    # TODO, create failure.html.erb
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.haml
= form_for @home, html: { class: "form-horizontal", role: "form" } do |f|
  -if @home.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@home.errors.count, "error")} prohibited this home from being saved:"

      %ul
        - @home.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :address, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :price, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :price, class: 'form-control'
  .form-group
    = f.label :agent, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :agent, class: 'form-control'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :description, class: 'form-control'
  .form-group
    = f.label :space, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :space, class: 'form-control'
  .form-group
    = f.label :parking, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :parking, class: 'form-control'
  .form-group
    = f.label :bedrooms, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :bedrooms, class: 'form-control'
  .form-group
    = f.label :bathrooms, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :bathrooms, class: 'form-control'
  .form-group
    = f.label :house_image, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.attachment_field :house_image
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/homes/edit.html.haml
.page-header
  = link_to homes_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @home, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing home

= render 'form'

app/views/homes/index.html.haml
.row
  - @homes.each do |home|
    .col-sm-4.col-sm-4.col-sm-4
      .thumbnail
        = image_tag(attachment_url(home, :house_image), style: "height: 200px")
        .caption
          %h4.pull-right= number_to_currency(home.price)
          %h4
            = link_to home.address, home
          %p
            = home.description

app/views/homes/new.html.haml
.page-header
  = link_to homes_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New home

= render 'form'

app/views/homes/show.html.haml
.page-header
  = link_to homes_path, class: 'btn btn-default' do
    Back
  %h1 House Description


%dl.dl-horizontal-offset
  %dt Address:
  %dd= @home.address
  %dt Price:
  %dd= @home.price
  %dt Agent:
  %dd= @home.agent
  %dt Description:
  %dd= @home.description
  %dt Space:
  %dd= @home.space
  %dt Parking:
  %dd= @home.parking
  %dt Bedrooms:
  %dd= @home.bedrooms
  %dt Bathrooms:
  %dd= @home.bathrooms
.img-thumbnail
  = image_tag attachment_url(@home, :house_image), size: "200x200"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = Minizill

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "#", class: "navbar-brand" do
            Minizill
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to homes_path, class: "navbar-brand"  do
                Home
            %li
              = link_to new_home_path, class: "navbar-brand" do
                %span.glyphicon.glyphicon-plus
                  New Home

          %ul.nav.navbar-nav.navbar-right
            - if logged_in?
              %li
                = link_to 'Logout', logout_path
            - else
              %li
                = link_to 'Login with Github', login_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/session/new.html.haml
.container
  .jumbotron
    %h1 Welcome to Minizill!
    %p
      = link_to 'Login with Github', login_path